
#ifndef LAB_REPO_CONFIG_H
#define LAB_REPO_CONFIG_H

#define PORT 8080
#define BUFF_SIZE 20480
#define BACKLOG 5
#define NODES_COUNT 20
#define FIXED_SIZE_STRING_LENGTH 40
#endif //LAB_REPO_CONFIG_H
